[package]
name = "decorator"
version = "0.1.0"
authors = ["Zhongpu Chen <chenloveit@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
